"""Добавлено поле avatar в модель User

Revision ID: 2621e6755a4b
Revises: 276e08c3a46c
Create Date: 2024-12-02 00:32:22.051016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2621e6755a4b'
down_revision = '276e08c3a46c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###
